#Sectors
climate_change <- "climate-change"
agriculture    <- "agriculture-agro-industries"
economic       <- "economic-financial-governance"
education      <- "education"
energy         <- "energy-power"
environmentt   <- "environment"
human          <- "human-capital-development"
health         <- "health"
information    <- "information-communication-technology"
infrastructure <- "infrastructure"
gender    <- "gender"
transport <- "transport"
water     <- "water-supply-sanitation"
